[environment]
python-version = "3.13"
python = ".venv"
root = ["./"]

[rules]
unresolved-import = "ignore"
unused-ignore-comment = "error"

[src]
include = ["src", "tests"]

[terminal]
error-on-warning = true
output-format = "concise"

[analysis]
replace-imports-with-any = [
    "prophet.**",
    "psycopg2.**",
    "sklearn.**",
    "pook.**",
    "testcontainers.**",
]
